### ISSUE TITLE
 Could not scan for classes inside...

### ISSUE THREAD

**Issue by reasonpun** [Hesto/multi-auth#1]
for help! I'm newer in laravel. 
and when i install multi-auth,it says:
```
reasonpun@vultr:/ebook$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files


  [RuntimeException]
  Could not scan for classes inside "/ebook/vendor/hesto/multi-auth/src/commands" which does not appear to be a file nor a folder


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```
thank you for helping me~

**Comment by Hesto** [comment]
Delete from your composer.json hesto/multi-auth and use commands :
```
composer self-update
composer clear-cache
composer update
composer require hesto/multi-auth
```

It should work.

**Comment by reasonpun** [comment]
use those commands,  i got the same exception.
and my composer is the lastest version: composer version 1.2.0 (stable channel).
my server is ：
Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64
PHP 7.0.7 (cli) (built: Jun 13 2016 16:12:37) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

but in homestead , it's ok!

thanks again.

**Comment by reasonpun** [comment]
![e0e4812d-340d-4d13-9c17-c04a7d3ef41b](https://cloud.githubusercontent.com/assets/880470/18335993/4bd178ec-75b6-11e6-9ff6-94a78c54d3d0.png)

i have a new laravel project ,but also can not install

**Comment by reasonpun** [comment]
![ec185b98-2320-493b-904f-7acb15ea515b](https://cloud.githubusercontent.com/assets/880470/18336083/03558e40-75b7-11e6-9acf-8219f8d2ce3c.png)

and can not find /data/web/project/vendor/hesto/core/src/commands, but /data/web/project/vendor/hesto/core/src/Commands exists

**Comment by Hesto** [comment]
I will make new version of hesto/core with new composer.json. Since last composer update smth changed in autoload.

**Comment by Hesto** [comment]
@reasonpun Try now, it should be fixed.

**Comment by reasonpun** [comment]
thx very much , it's ok~

but,
it's not ok , when my laravel version is laravel/framework (v5.3.6)
after updating to v5.3.7
![910dfb8a-6b53-4d84-8826-d9fe85199946](https://cloud.githubusercontent.com/assets/880470/18374832/cefdb6b4-7682-11e6-81c1-990ad7945590.png)
then,
use  
```
composer require hesto/multi-auth

```
![677b794c-5e2b-4b84-b288-c543239e91ca](https://cloud.githubusercontent.com/assets/880470/18374853/faec3bc4-7682-11e6-8dd3-3033ff9cbd8d.png)
it's ok!
thanks again~~

**Comment by Hesto** [comment]
I don't really know. But i think if you now install fresh copy of laravel you will be able to install multi-auth without any problem.
