### ISSUE TITLE
User Actions

### ISSUE THREAD

**Issue by odyright** [Hesto/multi-auth#10]
Hello @Hesto In addition to set Multi-auth, how to provide a way to authorize user (Admin or Employee) actions against a given resource? 
Laravel's default Authorization approach does it in a simple way.

**Comment by odyright** [comment]
For Authorization L 5.3 is built around 2 concepts : Gate & Policy..but i don't know to do it works with Multi Auth...

**Comment by Hesto** [comment]
I don't understand what do you want to do.

**Comment by odyright** [comment]
For exemple i created an app that handles student's registration. I have also 2 users (admin & employee) who can access the dashboard, i want that admin user been able to have all rights (view all students info,edit, delete etc) and the employee user... limited rights in the admin dashboard

**Comment by Hesto** [comment]
You can make that multi auth with this package but if you want to control access you have to use any ACL like https://github.com/Zizaco/entrust . But this package has nothing to do with your problem. Please dont open Issues if you have problem like that. Go to laracasts.com and ask community about that.
