### ISSUE TITLE
Freshly installed laravel 5.5 has an - (Auth guard [admin] is not defined.)

### ISSUE THREAD

**Issue by clvenk** [Hesto/multi-auth#109]
I have installed laravel 5.5 following the step, when i route to localhost:8000/admin/register i am getting error Auth guard [admin] is not defined. Please help me out

**Comment by KimKJDesigns** [comment]
I've just done a fresh install, set up an admin auth and can get that route fine. Perhaps just try to set up another project, just to confirm the issue.

**Comment by clvenk** [comment]
@KimKJDesigns it works fine if you clear cache, Thank you for your reply.. :)
