### ISSUE TITLE
Custom home route with data to /home view

### ISSUE THREAD

**Issue by prabhat2k15** [Hesto/multi-auth#111]
protected $redirectTo='brandadmin/home' is set for default home. But i am unable to send my data on the view. 
I have tried   Route::get('/home','BrandAdminController@index')->name('brandadmin.home');
also in web.php but its not working.

How can i send my custom data to /home view in multi auth system.???

**Comment by Ericndefo** [comment]
have the same issue

**Comment by Ericndefo** [comment]
you can use your "user" file into route folder , to passing data to "home" view

**Comment by prabhat2k15** [comment]
yeah that works...thanks.
