### ISSUE TITLE
It`s work in laravel 5.6?

### ISSUE THREAD

**Issue by osbre** [Hesto/multi-auth#126]
It`s work in laravel 5.6?
thanks...

**Comment by Hesto** [comment]
Yes

**Comment by Zugmaschine** [comment]
Did it work with Laravel 5.6?
And can i use it together with Standard make:auth?

**Comment by Ostap34JS** [comment]
@Zugmaschine, 1 question answer:
 https://github.com/Hesto/multi-auth/issues/135

**Comment by osbre** [comment]
@Zugmaschine , maybe create a new issue, and ask again
