### ISSUE TITLE
Undefined Offset 0

### ISSUE THREAD

**Issue by 1usman** [Hesto/multi-auth#131]
Trying to use on Laravel 5.6, after registering new auth it starts giving the following error on using artisan command to either migrate or perform any operation.

In Router.php line 1224:
                       
  Undefined offset: 0

**Comment by HoangDang2589** [comment]
check your RouteServiceProvider then add this function    
`protected function mapAdminRoutes()`
    `{`
        `Route::group([`
            `'middleware' => ['web', 'admin', 'auth:admin'],` 
            `'prefix' => 'admin',`
            `'as' => 'admin.',`
            `'namespace' => $this->namespace,`
        `], function ($router) {`
            `require base_path('routes/admin.php');`
        `});`
    `}`
