### ISSUE TITLE
Route [admin.login] not defined. Only home routes work.

### ISSUE THREAD

**Issue by dododaphne** [Hesto/multi-auth#138]
After I create two auth
```
php artisan multi-auth:install admin -f
php artisan multi-auth:install member -f
```

Here is my php  artisan route:list

```
URI                         Name
admin/home            admin.home
admin/login           login
admin/logout          logout
member/home           member.home
member/login          login
member/logout         logout
```

Only "admin/home" and "member/home" route name is correct(i.e., admin.home and member.home),  but others don't.

> The"admin/login" route name should be "admin.login", but in my route list, it shows "login", so when I use {{route('admin.login')}}, laravel throw an error "Route [admin.login] not defined."  Only the home routes that are working.

I've try composer update, composer dump-autoload -o, php artisan route:clear, but not working.
I'm using Laravel 5.7

**Comment by toksdotdev** [comment]
Still not clear on your question. Thanks. 

Is it that it's only the home routes that are working?

**Comment by dododaphne** [comment]
For example, the"admin/login" route name should be "admin.login", but in my route list, it shows "login", so when I use {{route('admin.login')}}, laravel throw an error "Route [admin.login] not defined."
 
Only the home routes that are working.

**Comment by dododaphne** [comment]
> After I create two auth
> 
> ```
> php artisan multi-auth:install admin -f
> php artisan multi-auth:install member -f
> ```
> Here is my php artisan route:list
> 
> ```
> URI                         Name
> admin/home            admin.home
> admin/login           login
> admin/logout          logout
> #other admin route name not prepend "admin."
> member/home           member.home
> member/login          login
> member/logout         logout
> #other member route name not prepend "member."
> ```
> Only "home" route prepend guard's name, but others doesn't work.
> 
> I've try composer update, composer dump-autoload -o, php artisan route:clear, but not working.
> I'm using Laravel 5.7

**Comment by dododaphne** [comment]
I believe the correct route list should look like this:
```
URI                         Name
admin/home            admin.home
admin/login           admin.login
admin/logout          admin.logout
member/home           member.home
member/login          member.login
member/logout         member.logout
```
