### ISSUE TITLE
Getting logged in user

### ISSUE THREAD

**Issue by agent2020** [Hesto/multi-auth#15]
How do i get the logged in user in the multi auth i just created like i'll check the number user with (Auth::check())

**Comment by Hesto** [comment]
pick one of:

```php
Auth::user();
Auth::guard()->user();
Auth::guard({guard})->user();
```

**Comment by tucq88** [comment]
I think last option is more accurate `Auth::guard({guard})->user();`

**Comment by Hesto** [comment]
They work if you use proper middleware (not only with default guard).
