### ISSUE TITLE
 [Illuminate\Contracts\Filesystem\FileNotFoundException]

### ISSUE THREAD

**Issue by squalvj** [Hesto/multi-auth#16]
i follow the tutorial till the end but when i want to type "php artisan multi-auth:install admin -f"
i keep getting these error.

 [Illuminate\Contracts\Filesystem\FileNotFoundException]
  File does not exist at path C:\{MY_LARAVEL_DIRECTORY}/routes/web.php

i currently use laravel 5.3
thank you

**Comment by Hesto** [comment]
is it a fresh copy of laravel? You should have this file.

**Comment by squalvj** [comment]
the problem is, i haven't directory "routes" and its files.
i think the problem is my laravel version, seems my version is 5.3 but in the very earler 5.3.
I just checkout with new fresh project and i found the "routes" directory inside my fresh project.
Case Closed. Thankyou man really appreciate it.
