### ISSUE TITLE
different admin route

### ISSUE THREAD

**Issue by ilidan85** [Hesto/multi-auth#20]
Is there any quick way to set different admin route but keeping admin guard?

`php artisan multi-auth:install admin -f`

but instead of `my-website.com/admin/login` I want to use `my-website.com/cms-name/login`

**Comment by Hesto** [comment]
Sure. Go to `app/Providers/RouteServiceProvider` and change method `mapAdminRoutes` to:
```php
protected function mapAdminRoutes()
{
        Route::group([
            'prefix' => 'cms-name', //change
            'as' => 'cms-name.', //change
            'middleware' => ['web', 'admin'],
            'namespace' => $this->namespace,
        ], function ($router) {
            require base_path('routes/admin.php');
        });
}
```

**Comment by ilidan85** [comment]
That makes sense :) Thanks for really great work you did there! I think you saved us lots of time!

**Comment by Hesto** [comment]
Thanks appreciate it. One more thing, copy and paste the method from my previous post again because i forgot to add `auth:admin` middlaware to array.

**Comment by ilidan85** [comment]
Dziękuję! That worked!
