### ISSUE TITLE
Passport Multi-Auth

### ISSUE THREAD

**Issue by SidharthRaveendran** [Hesto/multi-auth#21]
Looks like this package doesn't support multi-auth using Passport. I'm using Passport for the User API authentication but I'm unable to use it for Admin API authentication at the same time created using this package.

**Comment by Hesto** [comment]
I will test the package with Passport soon. Hope next week i will provide working solution.

**Comment by SidharthRaveendran** [comment]
I tried  working with the passport package but it seems passport wasn't built with the intention of having multi auth support.

**Comment by Hesto** [comment]
Lets continue in this topic: https://github.com/Hesto/multi-auth/issues/9
