### ISSUE TITLE
$redirectTo with param

### ISSUE THREAD

**Issue by ilidan85** [Hesto/multi-auth#24]
I want to set my redirect after logging in and logging out to route with dynamic param. Something like

`public $redirectTo = '/cms-name/en/home';`

This one above works fine but I need that "en" to be dynamic. How can I achieve that? 
Thanks a lot!

**Comment by Hesto** [comment]
Just add a method with logic, where you can set another $redirectTo. Then run the method in constructor.

**Comment by ilidan85** [comment]
Yea, but the problem is how to pass it to that constructor with login post()?
