### ISSUE TITLE
Not staying logged in

### ISSUE THREAD

**Issue by Gruutak** [Hesto/multi-auth#26]
Hi, in my template.blade.php I have the following code in the top of the page:

```
@if (Auth::guard("doctor")->user())
    Welcome, {{ Auth::guard("doctor")->user()->name }}
    <a href="{{ url('/doctor/logout') }}">Logout</a>
@endif
```

Right after registering or logging in, it show the welcome message, but when the user go to any other page the session is lost... I'm using the default login system provided by multi-auth... Any way to keep it logged in?

**Comment by Hesto** [comment]
Keep your doctor routes in routes/doctor.php then it should be fine.
