### ISSUE TITLE
Method mapEmployerRoutes does not exist

### ISSUE THREAD

**Issue by opheliadesign** [Hesto/multi-auth#28]
Followed setup instructions using `php artisan multi-auth:install employeer -f` (yes, I realize I spelled "employer" wrong, too tired). After everything is created, the following error appears:
```
[BadMethodCallException]                 
Method mapEmployeerRoutes does not exist.
```

`RouteServiceProvider.php` has this added, but the method is not in the class:
```
public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();

        $this->mapEmployeerRoutes(); // method not found

        //
    }
```

I created the missing method as so:
```
protected function mapEmployeerRoutes()
    {
        Route::group([
            'middleware' => 'web',
            'namespace' => $this->namespace,
        ], function ($router) {
            require base_path('routes/employeer.php');
        });
    }
```

This allows me to access `/employeer/login`, etc., and everything there works. But the `employeer/home` route returns a 404 error and is not listed when running `php artisan route:list`. What am I missing??

Laravel 5.3

**Comment by opheliadesign** [comment]
Ah, found a close issue that solved the problem. Perhaps add that tidbit to the directions?

**Comment by Hesto** [comment]
well, you should try will real english word. I have never try to setup it with wrong word. And i think it is important because i use [str_plural[(https://laravel.com/docs/5.3/helpers#method-str-plural) and [str_singular](https://laravel.com/docs/5.3/helpers#method-str-singular).

**Comment by opheliadesign** [comment]
Wow, a shot at spelling! I acknowledged this in my post, it was a typo. I also tried with other nouns, such as "employee" and "candidate." 

This is either a bug, code not being injected into RouteServiceProvider, or an important step left out of the documentation.

**Comment by opheliadesign** [comment]
You also reference str_plural and str_singular. What I am really hoping for is a path like `/candidates` or `/employers` but  your examples use a singular when setting up - `php artisan multi-auth:install employee -f`. This generates routes like `/employee/login`. Should this instead be plural? `php artisan multi-auth:install employees -f`?

By the way, running `php artisan multi-auth:install employee -f` also caused the `RouteServiceProvider.php` issue - missing method `mapEmployeeRoutes`.

**Comment by Hesto** [comment]
If you want plural guard names you can always fork the package and change what you need. For me singular is better and i will keep it.

**Comment by opheliadesign** [comment]
Fair enough. I really like and appreciate your package, but please update the docs to mention RouteServiceProvider. 

Thanks!

**Comment by opheliadesign** [comment]
Actually, the more I think about it, singular makes more sense. Thanks again, closing this issue.

**Comment by Hesto** [comment]
Cool, thanks. What do you mean about changing docs of RouteServiceProvider? It is written that the package changes this file. What else should i write there?

**Comment by opheliadesign** [comment]
It adds a reference to a route mapping method in RouteServiceProvider that is missing after executing your artisan command. This causes a missing method exception. There is a closed issue referencing this.  The solution is to create the missing method using the new guard, as you mention in the referenced issue. I'd link to it but I'm on my mobile.

**Comment by opheliadesign** [comment]
https://github.com/Hesto/multi-auth/issues/4
