### ISSUE TITLE
Redirect when access admin/* if not login

### ISSUE THREAD

**Issue by dinhchuong7913** [Hesto/multi-auth#29]
Hi
`Route::group([
            'middleware' => ['web', 'admin', 'auth:admin'],
            'prefix' => 'admin',
            'as' => 'admin.',
            'namespace' => $this->namespace,
        ], function ($router) {
            require base_path('routes/admin.php');
        });`
redirect /login when access admin/home if not login
if I remove 'auth:admin', it redirect /admin/login that I want but 
`$users[] = Auth::user();
    $users[] = Auth::guard()->user();
return null
why that?? and how to fix it.
Thanks

**Comment by Hesto** [comment]
with latest version of package it should be all ok.

**Comment by dinhchuong7913** [comment]
latest version is 1.7.  What do you mean?

**Comment by Hesto** [comment]
Your problem with redirection should be solved in 1.7. Check if you have have middleware RedirectIfNotAdmin

**Comment by dinhchuong7913** [comment]
yes, I installed 1.7 already. 
if I remove auth:admin, redirect to /admin/login correctly.
But home page, 
`Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();
    //dd($users);
    return view('admin.home');
})->name('home');`
![screen shot 2016-10-30 at 14 32 09](https://cloud.githubusercontent.com/assets/4782655/19835077/b6fb11bc-9ead-11e6-9183-612d19c26fec.png)
My web app is simple, only install your package

**Comment by tucq88** [comment]
I got the same situation. A strange one. It's not about package fails, it something related to Laravel Middleware stuff

**Comment by dinhchuong7913** [comment]
Can solve in http://laravel.io/forum/09-01-2016-laravel-53-auth-redirect-guests-based-on-guard
but I can not understand this issue

**Comment by tucq88** [comment]
It seems like problem is about Laravel redirecting with guards . So strange.

**Comment by dinhchuong7913** [comment]
https://josephsilber.com/index.php/posts/2016/07/10/authentication-improvements-in-laravel-5-3#table-of-contents
Maybe this is answer for that

**Comment by Hesto** [comment]
The problem is `\Illuminate\Routing\Middleware\SubstituteBindings::class` in app\http\Kernel.php:

If we delete this middleware from web group, all is fine but i am sure we can't just delete it. So to figure out what is going on, i deleted body of handle method of this middleware and when i do it the problem is back. So conclusion: The problem is existence of this middleware. I dont know how to solve it. We have to know what is this middleware for.

**Comment by squalvj** [comment]
change your 'unauthenticated' function in app/exception/handler.php to this:

```
protected function unauthenticated($request, AuthenticationException $exception)
    {
        if ($request->expectsJson()) {
            return response()->json(['error' => 'Unauthenticated.'], 401);
        }

        $middleware = request()->route()->gatherMiddleware();
        $guard = config('auth.defaults.guard');
        foreach($middleware as $m) {
            if(preg_match("/auth:/",$m)) {
                list($mid, $guard) = explode(":",$m);
            }
        }

        switch($guard) {
            case 'admin': //depends which guard you failed to auth
                $login = 'admin/login'; 
                break;
            case 'pengguna':
                $login = 'pengguna/login';
                break;
            default:
                $login = '/';
                break;
        }

        return redirect()->guest($login); 
    }
```

**Comment by tucq88** [comment]
@squalvj yeah pretty tricky hah ? I don't see any issue on Laravel repo but this problem 99.999999999999999999999999999999999999999999% because of Laravel Handler `unauthenticate` method.
