### ISSUE TITLE
Auth Route

### ISSUE THREAD

**Issue by odyright** [Hesto/multi-auth#3]
Hello @Hesto i installed your package into a new project all's fine, good job. i'm new and just started job with L5.3
that looks like a support request: 
i want to now with multi-auth how use roles and permissions in the right way (AUTHENTICATION access)? For example i want that a someone who is registered can't have access level to the admin dashboard... as much as i marked him as admin.

**Comment by odyright** [comment]
Shall i use middleware?

**Comment by Hesto** [comment]
In your /routes dir you have some different files:
- web.php - everyone have access to this routes
- {guard}.php - only users authenticated users has access (for example if you installed 'admin' guard only users from admin table can access routes from /routes/admin.php)

**Comment by odyright** [comment]
OK i understand. So if i want to redirect for exemple the admin after he is signed to the `home dashboard`, i should edit the `route/admin.php` and  create a new file called "home or dashboard" in the `ressources/views/admin` ?

**Comment by odyright** [comment]
?

**Comment by Hesto** [comment]
Yes and you have to change redirect path in your LoginController.
