### ISSUE TITLE
Login Redirecting Issue

### ISSUE THREAD

**Issue by GNSubrahmanyam** [Hesto/multi-auth#30]
Hi,

When I go to http://cms.dev/admin/home without login it is redirecting me to http://cms.dev/login 

![image](https://cloud.githubusercontent.com/assets/18217008/19879216/8b2f2c5c-a016-11e6-8af3-b11ff6b5be04.png)

**Comment by klaravel** [comment]
See this one.

https://github.com/Hesto/multi-auth/issues/22
