### ISSUE TITLE
php artisan multi-auth:install {guard} -f  doesn't work

### ISSUE THREAD

**Issue by adesight** [Hesto/multi-auth#32]
[Symfony\Component\Console\Exception\CommandNotFoundException]
 There are no commands defined in the "multi-auth" namespace.

**Comment by Hesto** [comment]
You just didnt register the package

```
public function register()
{
    if ($this->app->environment() == 'local') {
        $this->app->register('Hesto\MultiAuth\MultiAuthServiceProvider');
    }
}
```

ensure you have APP_ENV=local in your .env file
