### ISSUE TITLE
After changing DB name (connection) it takes default db name and throw error

### ISSUE THREAD

**Issue by ajayexpert** [Hesto/multi-auth#36]
I have two db for example 
**DB1**  is default for all user 
**DB2** for admin so i made two different connection first one **MySql** and second one is **MySql2** 
when i changed admin model connection i takes default connection and throw an error that table not exist,
here is my connection code in model i am using **laravel 5.3** 
`protected $connection = 'mysql2';`
so i am wrong or there is bug

**Comment by Hesto** [comment]
The package has nothing to do with db connection. You are missing something.

**Comment by ajayexpert** [comment]
You made a great package it saved my lots of time for that **Thanks a lot** and i figured it out where is the issue it is in the  

`
protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:admins',
            'password' => 'required|min:6|confirmed',
        ]);
    }
`

in the unique validation it is selecting default db but it changed it 
into this 
`unique:mysql2.admins`
and it works fine so again thanks a lot
