### ISSUE TITLE
Laravel 5.3 production usage

### ISSUE THREAD

**Issue by HamidVetr** [Hesto/multi-auth#40]
I have a question and it's, why do you say that only use these package for local development and not production? and what should I do if I want to use it for production? what would happen if I do? does it make my application less secure?

**Comment by Hesto** [comment]
Package only generate files and setup some settings. After installation you can even uninstall package couse you dont need it anymore. There is no reason to keep it in production packages, but if you want to keep it, you can.

**Comment by HamidVetr** [comment]
thanks man
