### ISSUE TITLE
Namespace issues in Laravel 5.3

### ISSUE THREAD

**Issue by keenminded** [Hesto/multi-auth#41]
@Hesto **Thank you** for a useful package!
Correct me if I am wrong, but the stubs need to have **{{namespace}}** instead of the default App\ being hard-coded? Just realized this after having to refactor things, since the package wasn't working for me.

Also, noticed that the **--domain** flag in the artisan command is missing or deprecated.
Thanks again, and keep up the good work!

**Comment by Hesto** [comment]
Domain flag will be working soon. Thanks for idea with namespace, ill add it in next version.

**Comment by Hesto** [comment]
Domain flag is working now. Update the package.

**Comment by keenminded** [comment]
@Hesto: Thank you for the quick response. Dziękuję!
