### ISSUE TITLE
admin is considered logged in even if he closed the browser and re open it!

### ISSUE THREAD

**Issue by mrmrn** [Hesto/multi-auth#43]
I used hesto package last night and when I login with laravel make:auth package as user ,after closing the browser I am logged out.
when I logged in as admin, even when I closed the browser admin is logged in yet!!
how can I set time out for admin to be logged in? and at least how to consider admin logout when he closed browser?
than you for the package.

**Comment by judia** [comment]
did you try creating a logout button? 

<a href="/logout">logout</a>
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

**Comment by mrmrn** [comment]
yes, loguot button works. but for example I want when  admin closed the browser he assumed logged out.
or when he enter as admin but he doesn`t work in site,the system conseder him as logged out person.
these two are for security especialy in admin guard.

**Comment by Hesto** [comment]
Go to Laracasts and ask there.

**Comment by ankurk91** [comment]
@mrmrn 

Change this in your ```config/session.php```
```
'expire_on_close' => true,
```

Read more here:
https://laracasts.com/discuss/channels/laravel/session-expire-on-close

**Comment by mrmrn** [comment]
thank you @ankurk91 .
