### ISSUE TITLE
Named Routes in Multi Auth Route files

### ISSUE THREAD

**Issue by agent2020** [Hesto/multi-auth#44]
whenever i create a new route in a guard route, when i call the route name from my controller, it throws errror saying the route name is undefined
Route [nameOfRoute] not defined.
Please assist me to solve this issue

**Comment by Hesto** [comment]
Show me your code.

**Comment by agent2020** [comment]
in routes/userauth.php
Route::get('home', 'Userauth\MainController@index')->name('index');
in app/Http/Controllers/Userauth/MainController.php
return redirect()->route('index')->with('message','user settings Updated Successfully ');

where Userauth is the name of a created guard and MainController is the controller in the Userauth folder, now when i give a return to redirect and link the index route name, it says Route [index] not defined.

**Comment by Hesto** [comment]
When you name route "index" in your {guard}.php file the name of route will be:
{guard.}index

**Comment by fahadhowlader** [comment]
Route with Controller not working for Admin
