### ISSUE TITLE
Lucid ? 

### ISSUE THREAD

**Issue by tucq88** [Hesto/multi-auth#45]
Have no idea about what `lucid` option is. Could some one explain or give me some ref links to learn more about it ? 😄

**Comment by Hesto** [comment]
@behind-design question for you :)

**Comment by Moudi2020** [comment]
https://github.com/lucid-architecture/laravel

**Comment by behind-design** [comment]
@tucq88 Lucid is an architecture structure for developing Laravel applications. If you wanna know a little bit more you can check this talk at Laracon this year, by one of its creators:

https://www.youtube.com/watch?v=wSnM4JkyxPw

Currently I'm developing a quite complex application that uses this architecture for structuring it, that way I'm able to share code while at the same time keep the different services separated.

If you have any doubts, just let me know :)

**Comment by tucq88** [comment]
Thanks for your answer @behind-design , much appreciated. 
As far as I could see it's something related to Clean Architecture or Hexagonal Architecture ? What kind of complex projects that recommend implementing with Lucid ? 
I'm just new to architecture stuff and still learning how to use and apply them correctly - so sorry if anything sounds dummy :P

**Comment by behind-design** [comment]
@tucq88 No not at all! Sorry for the delay!

For example right now I'm using lucid to build a project where essentially I have 3 kinda "subapps". I have to build an API for a mobile app, a website for a the team to upload videos and contents, and another website where the administration team handles statistics of the app and the other website. It handles authorization to allow or not allow specific content to be uploaded and seen in the app. As well as seeing reported content or anything else.

If I hadn't been using Lucid probably I'd have build 3 different apps, and find a way to share the same models and such. But with Lucid I'm able to share the models while having one code base. I can have separation in between the "apps", but at the same time I'm sharing code for specific jobs or concerns, which gives me a lot of power and flexibility when developing the project.


Does that help a little? Or am I losing you? hahaha

BTW, if you want there's a channel in Slack about Lucid in particular if you wanna join in.


Let me know if I can help you with anything!

**Comment by tucq88** [comment]
Wow, thanks alot @behind-design. It sounds really interesting to me, I'll join Slack and learn more about Lucid.
