### ISSUE TITLE
redirect back to intended page issue

### ISSUE THREAD

**Issue by Tajwebdeveloper** [Hesto/multi-auth#46]
I am having a UserAuth controller,
and i have added the Middleware to the route

```
Route::get('/', function () {
    return view('welcome');
})->middleware('user');
```

but when i try this after loggin in it should come back to home page instead of user/home,
how to change this i have changed this line in middleware RedirectIfUser

```
public function handle($request, Closure $next, $guard = 'user')
	{
	    if (Auth::guard($guard)->check()) {
	        //return redirect('user/home');
	        return redirect()->intended('user/home');
	    }
	    return $next($request);
	}
```

but no effect

the only where it's working is by changing in UserAuth/LoginController

`public $redirectTo = '/user/home';`

`to public $redirectTo = '/';`

but i dont want as i may have to add this middleware to multiple routes and after logging in it should remain on the protected routes and not go to the user/home..

**Comment by Hesto** [comment]
It should be change in LoginController of each guard. No middleware need. 
```
public $redirectTo = 'path_to_after_login_page';
```

**Comment by Tajwebdeveloper** [comment]
in the last part of the my question i did that, but the problem is i don't want a static path to redirect 
e.g. i have a route /profile which is in the middleware user, but when someone visits the page and type the /profile url it redirect to user/login page but after logging in it does not come back to the /profile page it goes to the $redirectTo path which is static.. if i dont use middleware how should i protect my route?

**Comment by Hesto** [comment]
when user type /profile and he needs to login it should redirect to /profile after login. It is default laravel thing. If it doesnt work, you broke smth.

**Comment by Tajwebdeveloper** [comment]
i am testing this on a fresh intallation of laravel.. so i dont think there is any chance i have broke anything

**Comment by Hesto** [comment]
You are missing smth. Maybe you login into wrong guard?

**Comment by Tajwebdeveloper** [comment]
i have just found out everything working exactly i want only the first time but once i logout and try to access the route again it does go to login page and than redirects to the user/home, but first time it works perfect see the 40 sec video 
http://neelnetworks.org/video/laravel.mp4
any solution for this?

**Comment by Tajwebdeveloper** [comment]
The issue is with the plugin, as i am having no issues if i use the built in laravel authentication by using make:auth command, i hope you'll figure out the issue.. it's not redirecting to the intented page after login please check

**Comment by behind-design** [comment]
@Tajwebdeveloper I'll have a look and get back to u!
