### ISSUE TITLE
Tokenmismatch exception on  existing project

### ISSUE THREAD

**Issue by InvertedX** [Hesto/multi-auth#47]
i tried to implement multiple authentication on my laravel 5.3 project. i used sub-domain routing for each authentication but when i tried to login it gives tokenmismatch exception . i added csrf field and still not woking 
i created a fresh laravel 5.3 install and it worked. what i m missing

**Comment by behind-design** [comment]
@InvertedX Sorry for the delay.

Have you created the `APP_DOMAIN=yourappdomain.app` key in you `.env` file?

Let me check a few things and I'll get back to you!
