### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by sonars** [Hesto/multi-auth#5]
The scaffolding generated for the {guard} has get request for logout which is actually supposed to be a post request. 

`Route::get('admin/logout', 'AdminAuth\LoginController@logout');`

replace with

`Route::post('admin/logout', 'AdminAuth\LoginController@logout');`

**Comment by sonars** [comment]
**_

> and thanks for the package. it's really great.

_**

**Comment by Hesto** [comment]
When i change method to post you wont be able to enter domain/admin/logout route, so you wont be able to logout

**Comment by odyright** [comment]
Hello @Hesto @sonars ..since the Laravel 5.3 logout is now with POST verb... how can we make the logout work for the admin guard? 
i tried it with the default `php artisan make:auth` in fresh installation ..it works. But doesn't with this repos....
help!

**Comment by Hesto** [comment]
Route::get('admin/logout', 'AdminAuth\LoginController@logout');

replace with

Route::post('admin/logout', 'AdminAuth\LoginController@logout');

**Comment by sonars** [comment]
Sorry to say but i forked the package and made a little tweaks around it as it is still allowing the logged in user to see login and registration pages.

If you are looking for the package please check it here [sonars/multiauth](http://github.com/sonars/multiauth)

and thanks for the awesome package Hesto.
