### ISSUE TITLE
Use separate password_resets_table for each 

### ISSUE THREAD

**Issue by ankurk91** [Hesto/multi-auth#51]
This package uses same database table (password_resets) for each guard.

But there is problem using this -
**Lets take an example :**
There are two types of users 
- Admin 
- Customer

An admin can be a customer and a customer can be an admin. Same person have two different account but with same email address.
Now when that admin user make any password reset request, application will overwrite any existing (this can be himself as customer) request for same email address. This way the tokens gets lost and email link becomes invalid.

The possible solution is to use a separate table for each user type -
*  Create a new ```admin_password_resets``` table 
```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateAdminPasswordResetsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('admin_password_resets', function (Blueprint $table) {
            $table->string('email')->index();
            $table->string('token')->index();
            $table->timestamp('created_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('admin_password_resets');
    }
}

```
*  Specify this table name in ```app/config/auth.php``` file

```php
'passwords' => [
        'admins' => [
            'provider' => 'admins',
            'table' => 'admin_password_resets',
            'expire' => 60,
        ],

        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],
```

* That's it, Laravel will use this new table for admins password reset tokens from now

**Comment by Hesto** [comment]
Thats good idea thanks. i will add it to the next version.

**Comment by ankurk91** [comment]
P.S.
Laravel 5.4 going to remove password reset table, see
https://github.com/laravel/laravel/compare/master...tillkruss:passwords

**Comment by Hesto** [comment]
Oh.. but why? Maybe there will by any artisan command.

**Comment by ankurk91** [comment]
checkout this PR
https://github.com/laravel/framework/pull/16850
