### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by joseluisq** [Hesto/multi-auth#58]
https://laravel-news.com/laravel-5-4

**Comment by Hesto** [comment]
It should work with 5.4 without changes, i will test it in 2 days i hope.

**Comment by joseluisq** [comment]
I have tested with Laravel 5.4 and doesn't work. 

For example, `app/Controllers/AdminAuth` controller directory is never called and when I try to navigate to `/admin` route this redirects to `/login` instead of `/admin/login`. 

It appears that `RouteServiceProvider->mapAdminRoutes()` method with `'auth:admin'` doesn't work in `Laravel 5.4`.

**Comment by Hesto** [comment]
Actually it works same way like in 5.3. 
The problem with wrong redirection is not connected with that package, but with laravel look: https://github.com/Hesto/multi-auth/issues/34

**Comment by joseluisq** [comment]
It's true, I have tested again (clean installation), works!
Sure, "same session" issue (wrong redirection) could be handled into the application itself. 
But I hope you can provide some solution for that in future versions.

I'll close this issue.
