### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by mastys100** [Hesto/multi-auth#60]
This is the error i get when trying to migrate
`Method mapAdminRoutes does not exist.`
I checked the RouteServiceProvider.php and the happens that there is no method defined for `mapAdminRoutes ` for i defined one myself but i don't know if i did the right thing.

`
private function mapBackadminRoutes()
    {
        Route::group([
            'middleware' => 'backadmin',
            'namespace' => $this->namespace,
            'prefix' => 'backadmin',
        ], function ($router) {
            require base_path('routes/backadmin.php');
        });
    }
`

Help!

**Comment by Hesto** [comment]
Did you use package with fresh laravel installation?

**Comment by mastys100** [comment]
No it's an already existing project.

**Comment by Nemermel** [comment]
Greetings. Trying to login as registered user, I have such message: 
http://imgur.com/a/oMNLO
Just initialized project, and made multi-auth users.
