### ISSUE TITLE
Update package.. and Cancel guard

### ISSUE THREAD

**Issue by kmunirawi** [Hesto/multi-auth#61]
Hello, your efforts are highly appreciated.
1st Question: Is there direct method to delete/cancel guard? (of course without deleting files manually).

2nd Question: How to update the package for recent update?

Regards

**Comment by Hesto** [comment]
1. No
2. composer update (package will be updated, but i do not recommend reinstall guard, it wont work well)

**Comment by kmunirawi** [comment]
Hello, thanks for answer.

Still having problems using this package.

I work on localhost, and used this artisan command to generate guard:

php artisan multi-auth:install employee -f --domain

because i want to  upload the project to sub-domain on line,
Also added  (APP_DOMAIN=yourdomain.com) to my .env file.

Cant use ( http://project/employee/login ) to test!

Note: It worked well when i used  ( php artisan multi-auth:install employee
-f) without sub-domain config.


Later, i want to work on change login to id, instead of email.

How can i resolve this problem. plz?

**Comment by Hesto** [comment]
@behind-design wrote this part.

**Comment by kmunirawi** [comment]
Ok, thanks v.much. Wainting clarification from @behind-design , thanks to him in advance.

Now, I've installed fresh copy (L5.4.9): Testing guards without (--domian) option works perfect. Ecxept the redirect if not logged in. try to read temp solutions suggested before, waiting for the fix.

Olso tested the guards with (--domian) option, and works perfect on a sub-domain online.

My question is: Is it possible to locally (in the development invironment ) test the guards installed with (--domain) option? 
If not, means that i need to install the guards after uploading the project online. which mean installing guards with (--domain) option while thay are currently available in the project !, i don't know what might happen .

Thanks in advance. Regards
