### ISSUE TITLE
Readme: Note about development only 

### ISSUE THREAD

**Issue by ankurk91** [Hesto/multi-auth#64]
Since this package is using ```LogsoutGuard``` trait  in ```LoginController```, it is not possible to use this package in development only.
If someone install this package using -
```
composer require hesto/multi-auth --dev
```
And then on production -
```
composer install --no-dev
```
The application will break, because it wont be able to load ```LogsoutGuard.php``` that comes from ```vendor``` folder.

We should instruct user to either copy the trait to ```app/Traits``` or package should install this trait to ```app/Traits``` . So that package can be used other than local environment safely.

**Comment by tucq88** [comment]
I only recognize this after deploy app to production, it's likely a BREAKING change to old users like me. I don't even see any informs in README.
