### ISSUE TITLE
How can I use middleware for admin in my route in laravel 5.4?

### ISSUE THREAD

**Issue by marn65** [Hesto/multi-auth#66]
Hi,
I am using this code in laravel 5.4
`Route::prefix('admin')->middleware(['web', 'admin', 'auth:admin'])->group(function(){
  Route::get('/{id}', 'AdminController@index');	

});`

but it uses basic laravel user login not admin login from the admins table.
How can I check If the user is not admin go to /admin/login?

**Comment by ankurk91** [comment]
@marn65
All routes defined  in your  ```routes/admin.php``` is protected by ```admin``` middle-ware already. It means no other than admin user can access these routes.

**Comment by marn65** [comment]
thank you
