### ISSUE TITLE
how to change login items?

### ISSUE THREAD

**Issue by marn65** [Hesto/multi-auth#69]
I am using default laravel 5.4 auth and I changed email to mobile number.
So in  AuthenticatesUsers trait 
```
 public function username()
    {
        return 'email';
    }
```
I changed email to mobile.

Now that I am using hesto ,I am using email for admin registration. but hesto is using that method exactly!!
How can I modify for admin login with email?

**Comment by ankurk91** [comment]
@marn65 
You are free to modify registration logic in
```
app\Http\Controller\{Guard}Auth\RegisterController.php
````
This package does not force you to use email during registration.

**Comment by codepotato** [comment]
@marn65 did you solve your issue here?

**Comment by mrmrn** [comment]
I edited registercontroller and it works now.

**Comment by folkevil** [comment]
@codepotato i'm trying to modify LoginController (post login method) but cannot found where is it, can you help ?

**Comment by codepotato** [comment]
@folkevil Might be worth creating a new issue for this as opposed to hijacking this one :) That said, the method you're after is in app\Http\Controller\{Guard}Auth\LoginController.php
