### ISSUE TITLE
Authenticated User

### ISSUE THREAD

**Issue by santoshachari** [Hesto/multi-auth#7]
Hey Piotr,

Thanks for the plugin - saved me so much time!. 

So I see: 
```
$users[] = Auth::user();
$users[] = Auth::guard()->user();
$users[] = Auth::guard('admin')->user();
```

On routes/admin.php all give a "Admin" object, even though default guard is "web", which should give "User" object. 

When I specify the guard as "web" it shows a "User" object. 

Is that a bug, or something one should watch out for? 

Thanks in Advance.

**Comment by Hesto** [comment]
Look at file `app/Providers/RouteServiceProvider.php`. There are attached middlewares responsible for that.
