### ISSUE TITLE
Get the user id

### ISSUE THREAD

**Issue by chizzycrusty** [Hesto/multi-auth#70]
Hey, I use this package because I need to manage 3 types of account. So I followed what this package installed: separated views, models, controllers... Each of the account types has it's post table, controllers...
So, how can I get the user id to create a post as:
$post->user_id = Auth::user()->id; 
gives an error ?

**Comment by chizzycrusty** [comment]
$user = $request->user('yourguard');
$post->user_id = $user->id;
did the job, you can close the issue

**Comment by ankurk91** [comment]
@chizzycrusty 
Here are two more ways -
```php
# via facade
\Auth::user('guard)->id;

# via helper
auth('guard')->user()->id
```
