### ISSUE TITLE
Users Logging in at the same time on different guards

### ISSUE THREAD

**Issue by santoshachari** [Hesto/multi-auth#74]
Hi there! thanks for this wonderful plugin 

I am trying to figure how to allow two users to login in` /login,` and `/admin/login `at the same time. If the user is logged in `/login`,` /admin/login` redirects to /home.

**Comment by codepotato** [comment]
Out of interest, why would you need them to be logged in under two guards? I don't think Laravel itself can handle that?

**Comment by Ljz7** [comment]
The interest is that you can configure the website form the BO while testing the result as user on the FO. So you don't have to login/logout, again and again... and again. 

But maybe there's a better solution ? How do you usually deal with it @codepotato ?

**Comment by codepotato** [comment]
Ah, so allowing an admin to login as a different user role? 

Firstly, you wouldn't necessarily need two auth guards for that, but the way I've tackled this in the past is to store the UUID or Admin user ID in the session as you log in as the user. Then, when the user clicks logout, write your own logic to handle the logout that looks for the admin user id, and if it exists, programmatically log that admin user back in. 

Clearly, for this you would be best storing the session data outside of the browser (using the database driver, for example) but it's a simple solution to that.

**Comment by codepotato** [comment]
E.g. Session::put('admin_user_id', Auth::guard('ENTER GUARD HERE')->user()->getKey() );

Then, in the logout function: 

if( Session::has('admin_user_id') )
{
Auth::guard('ENTER GUARD HERE')->login( Model::find( Session::get('admin_user_id') ) );
}

**Comment by santoshachari** [comment]
@codepotato Thanks! 

It was mostly for testing. I did however have cases where an "employee" for one local outlet could only be a "customer" on the front end for another outlet. Guess it's not much of an effort to open another browser or logging in and logout. 

I somehow thought it was working before a user could go `/admin/login` without being redirected to `/user/home` if logged in.

**Comment by codepotato** [comment]
@santoshachari I suppose you could add the new guard middleware to the route you're trying to access, so they're not redirected, but I reckon it'll be more hassle than it's worth, especially as any check for 

`Auth::user()`

Will default to the standard guard of Laravel, rather than your new one. 

That's what this package does, it creates a complete clone of the existing Laravel auth, but sadly they don't necessarily work side-by-side if you want a user to jump from one auth guard to another.

**Comment by santoshachari** [comment]
Agreed... I do think it was worth a discussion! Thanks @codepotato

**Comment by codepotato** [comment]
Very welcome :)
