### ISSUE TITLE
NotFoundHttpException in RouteCollection.php

### ISSUE THREAD

**Issue by dominik04u** [Hesto/multi-auth#78]
I made everything like in instruction, but when I try use url it throws NotFoundHttpException in RouteCollection.php

http://stackoverflow.com/questions/43865524/laravel-hesto-multi-auth-notfoundhttpexception/43866844?noredirect=1#comment74769585_43866844

**Comment by isLishude** [comment]
The right url is `student.yourdomain.com/login`

You can edit your HOSTS file,but you can‘t direct use `php artisan serve`,you should use [Homestead](https://laravel.com/docs/5.4/homestead),or deploy code in Linux+PHP+Nginx+MySQL.

I prefer use Homestead.

Example: 

my HOSTS:
```
192.168.10.10 dev.app
```
my homestead.yaml

```
ip: "192.168.10.10"
```
