### ISSUE TITLE
Redirect after logged in

### ISSUE THREAD

**Issue by haipham** [Hesto/multi-auth#8]
Thank for your work.

I'm a new to Laravel.

I created employee auth, when I login with "http://multiauthl3.dev/employee/login", employee user redirected to "http://multiauthl3.dev/employee/home" after authenticated success. Then I access "http://multiauthl3.dev/employee/login" again, I must login again with email and password, employee session not exist.

Please help. Thank you.

**Comment by Hesto** [comment]
Thank you @haipham for that report. In new version (1.7) i will add new middleware which will fix the problem. I will public this version today probably.
