### ISSUE TITLE
Multi Auth fails Route::group(['middleware' => 'auth'])

### ISSUE THREAD

**Issue by smn1234** [Hesto/multi-auth#80]
If I create another type of users like admin. They still can't access the routes that are wrapped by the default auth middleware. What if I have a page that needs to be accessed by regular users and admins? Is there a way to do it?

**Comment by isLishude** [comment]
I found the solution, you can try this:

You should edit  `app\Providers\RouteServiceProvider.php

```php
  protected function mapAdminRoutes()
    {
        Route::group([
            // delete web middleware option
            'middleware' => ['web','admin', 'auth:admin'],
            'prefix' => 'admin',
            'as' => 'admin.',
            'namespace' => $this->namespace,
        ], function ($router) {
            require base_path('routes/admin.php');
        });
    }
```

Just delete web middleware
