### ISSUE TITLE
L5.5: Please enable support for Package Auto-Discovery

### ISSUE THREAD

**Issue by fancenl** [Hesto/multi-auth#89]
See https://github.com/barryvdh/laravel-debugbar/pull/643/commits/1a206a491e1a24d4f5555dafad3d742064c3a20d

Makes it a lot easier and cleaner! :)

**Comment by Hesto** [comment]
It will be implemented soon :), thanks.

**Comment by fancenl** [comment]
Great, thanks so far! Great package!

**Comment by Hesto** [comment]
Done :)

**Comment by fancenl** [comment]
Hero!
