### ISSUE TITLE
Not working with Laravel 5.5

### ISSUE THREAD

**Issue by yogeshkoli** [Hesto/multi-auth#90]
`[ReflectionException]                                                             
Method Hesto\MultiAuth\Commands\MultiAuthInstallCommand::handle() does not exist `

Is it supports Laravel 5.5 yet?

**Comment by shsbd** [comment]
![method-hesto-multiauth-commands-multiauthinstallcommand-handle-does-not-exist](https://user-images.githubusercontent.com/12555542/30129386-8abeb4a0-9367-11e7-9a8d-d0be4790ccee.png)

The Same issue is happening on my end.

Laravel Framework 5.5.2
PHP 7.1.5

> **php artisan multi-auth:install user -f**

```
[ReflectionException]
Method Hesto\MultiAuth\Commands\MultiAuthInstallCommand::handle() does not exist
```

**Comment by Hesto** [comment]
uninstall package and install again (new version 2.0 for laravel 5.5)

**Comment by yogeshkoli** [comment]
@Hesto & @dneykov Thank you for the new version update, it working with Laravel 5.5.
